### ISSUE TITLE
[DISCUSSION] Yearly report page 

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/sosc-website#113]
Hey, Everyone :wave:
We had planned for weekly newsletters but it didn't work out as we planned 😅 we gonna have to prepare an yearly report page in the website with all the details of activities and events happened in this year. Let's keep the deadline to around mid of December, we gotta send out mails to entire college :fire:

- It should be beautiful
- Contents can be about blog posts, events and other activities we conducted
- Have to include the details of new members and the new team with their responsibilities

If multiple people are working on it we gotta divide the work by giving each of them each component to work on. But, the design comes first. Everything will follow after reviewing the design 😁 So, our design team will be involved in this and their work is put into highest priority.

**Comment by ghost** [comment]
😇

**Comment by haxzie-xx** [comment]
It'll be of really great help, if everyone can drop in their suggestions on what to include :smiley: in the yealy report.

**Comment by dhanushp** [comment]
IN

**Comment by nathanielmathew** [comment]
👍

**Comment by rumaan** [comment]
Is gonna be like a seperate section in the website or a Unique URL/Slug to it? @haxzie

**Comment by chaman-1** [comment]
Section maybe

**Comment by haxzie-xx** [comment]
@rumaan Yes, a seperate page!
We can take Inspirations from the following reports
- [Stackoverflow's 2017 report](https://insights.stackoverflow.com/survey/2017), the header looks cool :heart: 
- [HackerRank Annual Developer skill report](https://research.hackerrank.com/developer-skills/2018/)
- [Octoverse GitHub](https://octoverse.github.com/), We can probably create something similar

**Comment by afrzhussain** [comment]
Sounds interesting . Devide the jobs and set due dates for each

**Comment by charmy11** [comment]
V could add the progress made
And those graphs looks good.. V could. Use them.

**Comment by haxzie-xx** [comment]
Any updates on this @Dhanush-Bangera @nathanielmathew ?

/remind us to start the development of the yearly report page on Dec 10

**Comment by shravan1998** [comment]
Whats the progress right now?😅

**Comment by haxzie-xx** [comment]
Idk, if you guys are free.. please feel free to start. Collect the data from everyone, and summarize it. Cc: web and design team

**Comment by rumaan** [comment]
🌚

**Comment by nathanielmathew** [comment]
So, let's finish this off and get it out of the way. 
What kind of data can we use to show our growth? Drop suggestions👇

**Comment by nathanielmathew** [comment]
We can include: 

- The start of  the Sahyadri MLG group
- Rustathon
- Devhost:18
- Acquisition of 110 Community Members
- HacktoberFest HackNight 
- The various workshops conducted by students of the community

Anything else? 
We need everyone's  thoughts and suggestions. Drop them below! ✨

**Comment by chaman-1** [comment]
Mentored PU students during SSTH. Various student ambassadors.

**Comment by rumaan** [comment]
Anyone working on this rn?🍦

**Comment by haxzie-xx** [comment]
@nathanielmathew

**Comment by nathanielmathew** [comment]
Check the yearly report branch. I've sent a new PR with some improvements and included images. If anyone's free, review it and merge it if it's satisfactory
