### ISSUE TITLE
[BUG] Feedback button link takes to registration link

### ISSUE THREAD

**Issue by dhanushp** [so-sc/sosc-website#165]
When Feedback button is pressed, it takes to registration form instead of Feedback form.

**Comment by nathanielmathew** [comment]
For the flutter workshop? Seems to be working fine for me

**Comment by dhanushp** [comment]
@nathanielmathew Try once again. It still goes to Registration form while pressing feedback button. Even Musthaq is facing same issue

**Comment by nathanielmathew** [comment]
Yeah, when I reload the page, I get the same issue.;
But when I navigate to it from the home page, it  seems to be working fine

**Comment by haxzie-xx** [comment]
This bug still exists. Lot of participant's yesterday was complaining about this.
