### ISSUE TITLE
Create connect page with links to all of our community channels

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/sosc-website#187]
It'd be great to have a separate page on our website with links to all the community channel including telegram notification channel and telegram members group (we can setup a google form script to mail them the members group link).

**Comment by afrzhussain** [comment]
We can connect a form to the . Become a member button right???

**Comment by afrzhussain** [comment]
Or add the telegram and all social media links as icons in the website . In the footer ( as how git nd all given )

**Comment by haxzie-xx** [comment]
Yeah, we can use that to onboard them into the Members group. But let's keep the Notification Squad and Google Mailing List open for all.

**Comment by afrzhussain** [comment]
Okay lets make a different page for connecting to different groups . Also maybe for different verticals tooo . Like who are interested on a particular tech stack different group for each techstack. (Web OR Android or ML)  we can train them maybe

**Comment by haxzie-xx** [comment]
Examples for some similar pages..

https://nodejs.org/en/get-involved/

https://probot.github.io/community/ ❤️

**Comment by haxzie-xx** [comment]
@coderhawk999 @hm-bilal You guys wanna work on this?

**Comment by afrzhussain** [comment]
Not stale

**Comment by haxzie-xx** [comment]
@coderhawk999 any updates on this?

**Comment by afrzhussain** [comment]
Ive got my lab exams in coming days . Maybe will work on after wed
