### ISSUE TITLE
[BUG] Overlapping text in events listing

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/sosc-website#189]
## Current Behaviour
The Date in the event listing cards gets overlapped when refreshing the page in Mobile devices.
![Screenshot_20190418-104758](https://user-images.githubusercontent.com/18684321/56338502-e501d700-61c7-11e9-97cf-755143d32e72.jpg)

**Comment by afrzhussain** [comment]
not stale

**Comment by afrzhussain** [comment]
ive tried to fix this BUG. check PR #201  review and check if the bug is completely fixed or not 
@haxzie  or any better way to fix this.

**Comment by haxzie-xx** [comment]
Looks good to me :+1: Good job @coderhawk999
