### ISSUE TITLE
Event Markdown files have varible text sizes

### ISSUE THREAD

**Issue by akshayrb22** [so-sc/sosc-website#239]
After updating the markdown for an event, checking the preview before making a PR shows us text in varying sizes. For example:
![image](https://user-images.githubusercontent.com/30366482/66213282-0d7d7f00-e6dd-11e9-9e0e-b8c7744a4544.png)
Maybe it's a GitHub markdown issue. If it is let's update the README in the repo to reflect how to deal with these font problems.

**Comment by nathanielmathew** [comment]
I can try handling this one
