### ISSUE TITLE
Prevent "Register Now" / "Give feedback" button from disappearing behind footer

### ISSUE THREAD

**Issue by nathanielmathew** [so-sc/sosc-website#240]
While scrolling down on any of the event's pages, the "Register Now" / "Give feedback" button seems to disappear behind the footer container of the webpage.
It would be much more convenient if it is made to rest at the bottom of the Event page when the scrolling limit is achieved.

**Comment by afrzhussain** [comment]
Maybe changing color of button would help after reaching footer

**Comment by nathanielmathew** [comment]
@coderhawk999 I did think of that, but it would interfere and cover the footer links and it's other content

**Comment by dhanushp** [comment]
Make it sticky at the bottom?

**Comment by nathanielmathew** [comment]
@coderhawk999 could you add the relevant labels to this issue

**Comment by haxzie** [comment]
@nathanielmathew The button is designed to be hidden behind the footer because there are clickable links in the footer which might get overlayed by the button. It's not a bug.

**Comment by haxzie** [comment]
Fixed by @Phe0 on #256 :+1:
