### ISSUE TITLE
Bring that damn footer down

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/sosc-website#36]
Make the footer stay at the end of the page.

**Comment by jenniferabowd** [comment]
I might be able to help. It looked good when I looked at it. Where is this happening?

**Comment by haxzie-xx** [comment]
The contents of the website are enough to fill the viewport now. If the contents is less, you'll be able to see that. A quick way to recreate the issue is by zooming out in the events page.

**Comment by haxzie-xx** [comment]
@jenniferkaplannyc I guess we got a PR for the same issue, If you wish, u can try improving it. Or else I'll be closing this issue.

@davidbru Thanks for the PR, Please consider looking at the issue if anyone else is working on it before submitting PRs. :+1:

**Comment by davidbru** [comment]
@jenniferkaplannyc sorry I didn't mean to steal the issue from you.

**Comment by jenniferabowd** [comment]
It's okay, it happens. Luckily I didn't start working on this.
