### ISSUE TITLE
Convert the tabs to bottom navigation on mobile devices. 

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/sosc-website#37]
Create bottom navigation with icons instead of tabs in mobile devices.

Remove the fixed top navbar for more space in small screens.

**Comment by petervasil** [comment]
Hello, can I work on this one?

**Comment by haxzie-xx** [comment]
Sure, Go ahead :+1: don't forget to use some cool icons instead of texts 😉

**Comment by petervasil** [comment]
Hello, I fixed the issue, I created new local branch, but I am not able push to my changes into your project. Maybe I don`t have privileges? Thanks :)

**Comment by haxzie-xx** [comment]
Fork this repository to your account and add the git url of your repository.
First remove the current remote origin.  

 
```sh
git remote rm origin
```
Then
```sh
git remote add origin https://github.com/YOURUSERNAME/sosc-website.git
``` 

Finally submit the pull request :)
