### ISSUE TITLE
Create new layout for Member details page. 

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/sosc-website#39]
- create new layout and template
- Add option to view volunteered events
- Add ability to view blog post under user
- Prepare showcase for individual or collaborated projects
- convert to a portfolio or resume

**Comment by rumaan** [comment]
🌚

**Comment by haxzie-xx** [comment]
@rumaan Any plans on working on this? :new_moon_with_face:

**Comment by rumaan** [comment]
@haxzie Well I was working on it. The base responsive layout is done. Haven't put anymore work into it. I'll continue with it soon. :sleeping:
