### ISSUE TITLE
Improve image loading

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/sosc-website#40]
Improve image loading experience with lazy loading or medium like loading using plugins.

**Comment by petervasil** [comment]
Hello, can I work on this one?

**Comment by davidgorel** [comment]
Hello, can I work on this one?

**Comment by haxzie-xx** [comment]
Sure, Go ahead :+1:

**Comment by haxzie-xx** [comment]
Solved in #109 :+1:
