### ISSUE TITLE
Add React-Helmet tags for meta details on layout templates

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/sosc-website#72]
Use React helmet to apply meta tags based on post/event title and caption for improving SEO of the website. The files you need to update are in `src/templates` improve the site's social media sharing information through appropriate meta tags inside React Helmet.

**Comment by DominikTrojcak** [comment]
I would like to work on this

**Comment by haxzie-xx** [comment]
@DominikTrojcak sure go ahead! :+1:

**Comment by DominikTrojcak** [comment]
@haxzie 👍. Can you assign issue on me please?

**Comment by haxzie-xx** [comment]
I won't be able to assign an issue to u unless you are a collaborator or part of a same organization the repo is hosted in. You can work on the issue regardless ;)

**Comment by haxzie-xx** [comment]
Solved in #99 :+1:
