### ISSUE TITLE
Profile photos in Team page shrinks on mobile devices

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/sosc-website#97]
The profile images of team members with long name or designations seems to shrink on mobile devices/smaller screens. This might be due to flex box, I think it can be solved by giving the image fixed height and width.

**Comment by haxzie-xx** [comment]
@coderhawk999 @hm-bilal Would you guys like to check up on this? This is still unresolved.

/remind me to update the status of this issue on 20th December

**Comment by afrzhussain** [comment]
Il check on it il try to fix tommorow

**Comment by haxzie-xx** [comment]
Cool :+1: get @hm-bilal too with you so he can understand the codebase better.
